name: randommo
description: A Flutter MMO game with GetX and Firebase

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # GetX pour la gestion d'état
  get:

  # Firebase
  firebase_core:
  cloud_firestore:
  firebase_auth:

  # Utilitaires
  uuid:

  # UI
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
